spring:
  datasource:
    url: jdbc:mysql://database:3306/knut_db
    username: knut_user
    password: knut_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

logging:
  level:
    com.hackathon.knut: DEBUG
